# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: aircraft-appconf
  namespace: aircraft
  annotations:
    version: v1.0.0
    description: "Aircraft demo application"
spec:
  components:
    - componentName: aircraft
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: aircraft-ingress
            spec:
              rules:
                - paths:
                    - path: "/aircraft"
                      pathType: Prefix
